import Head from 'next/head'
import Challenge from '../components/Challenge'
import styles from '../styles/Challenges.module.css'

export default function Challenges() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Challenges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Challenges
        </h1>

        <Challenge title="Tony Morrison" description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. At senectus aliquet pretium nulla tincidunt. Aliquam ac donec pulvinar faucibus." />
        <Challenge title="Dystopians" description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. At senectus aliquet pretium nulla tincidunt. Aliquam ac donec pulvinar faucibus." />
        <Challenge title="Morality in Literature" description="Lorem ipsum dolor sit amet, consectetur adipiscing elit. At senectus aliquet pretium nulla tincidunt. Aliquam ac donec pulvinar faucibus." />
      </main>

    </div>
  )
}
