import Head from 'next/head'
import Challenge, { IChallenge } from '../components/Challenge'
import styles from '../styles/Challenges.module.css'
import { firestore } from '../config'

interface ChallengesProps {
    challenges: IChallenge[];
}

export default function Challenges({challenges}: ChallengesProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Challenges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Challenges
        </h1>

        {challenges.map(challenge => <Challenge key={challenge.id} {...challenge} />)}
      </main>

    </div>
  )
}

export async function getServerSideProps(context: any) {
    let challenges: IChallenge[] = [];
    const querySnapshot = await firestore.collection('challenges').get();
    querySnapshot.forEach(doc => {
        challenges.push({id: doc.id, ...doc.data()} as IChallenge);
    });

    return {
      props: {
          challenges
      },
    }
  }
  